### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tuomashatakka** [germtb/atom-jump-block#2]
This seems to be a problem with newer atom versions.

1. Activate package
2. Hold alt and press up/down

**Atom**: 1.20.0-beta5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [alt-up](https://github.com/germtb/alt-up-atom) package 0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\tuoma\.atom\packages\alt-up\lib\alt-up.js:54

TypeError: Cannot read property 'length' of undefined
    at nextBlockRow (/packages/alt-up/lib/alt-up.js:54:25)
    at cursors.forEach.cursor (/packages/alt-up/lib/alt-up.js:25:29)
    at Array.forEach (native)
    at HTMLElement.atom.commands.add (/packages/alt-up/lib/alt-up.js:24:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.0-beta5/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.20.0-beta5/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.20.0-beta5/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.0-beta5/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.0-beta5/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.0-beta5/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -4:02.9.0 core:select-all (input.hidden-input)
  3x -4:00.4.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -3:59.6.0 editor:consolidate-selections (input.hidden-input)
     -3:59.6.0 core:cancel (input.hidden-input)
     -3:59.1.0 intentions:highlight (input.hidden-input)
     -3:58.9.0 settings-view:open (input.hidden-input)
     -3:54.3.0 core:confirm (input.hidden-input)
     -3:07.9.0 application:open-file (input.hidden-input)
  8x -2:25.9.0 core:backspace (input.hidden-input)
     -2:20.1.0 intentions:highlight (input.hidden-input)
     -2:19.8.0 core:save (input.hidden-input)
     -2:18.9.0 intentions:highlight (input.hidden-input)
     -2:18.7.0 core:close (input.hidden-input)
     -1:03.9.0 core:select-all (input.hidden-input)
     -1:03.1.0 core:confirm (input.hidden-input)
     -0:11.1.0 alt-up:down (input.hidden-input)
```

### Non-Core Packages

```
aeons-ui 0.0.10 
alerion-syntax 0.0.3 
alt-up 0.4.1 
atom-clock 0.1.13 
atom-hot-package-loader 0.5.1 
atom-ternjs 0.18.3 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.7.0 
autoreload-package-service 0.0.4 
busy-signal 1.4.3 
color-picker 2.2.5 
eq-ui 0.0.0 
eslint-snippets 0.1.2 
file-type-icons 1.3.4 
flow-ide 1.8.1 
fold-comments 0.6.0 
git-log 0.4.1 
git-plus 7.9.3 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
language-babel 2.73.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flow 5.6.1 
linter-nplint 0.3.25 
linter-ui-default 1.6.7 
linter-ui-docks 0.0.0 
linter-ui-hinted 0.0.4 
path-hyperclick 0.3.0 
pigments 0.40.2 
point-black-syntax 0.0.0 
power-bar 0.0.1 
process-palette 0.15.0 
react-redux-es6-snippets 0.1.3 
reduced-dark-ui 0.7.2 
redui-jm-syntax 1.4.0 
symbol-gen 1.3.1 
synesthete 0.0.6 
tool-bar 1.1.0 
tool-bar-gui 0.1.2 
webbox-color 0.5.9 
```

**Comment by germtb** [comment]
Sorry I think this happened because I renamed the project (I think the previous name was not good) but forgot to unpublish it, while not mantaining it. You can download the newest version of the current plugin: https://atom.io/packages/atom-jump-block
